name: Build

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

permissions: {}

concurrency: 
  group: ${{github.workflow}}-${{github.event_name}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    name: Build Ports
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup MSVC Environment
      uses: mbeckh/cmake-utils/msvc-dev-env@master

    - name: Configure
      uses: mbeckh/cmake-utils/configure@master
      with:
        build-root: build
        source-dir: test
        binary-dir: build/ports
        extra-args: -D "CMU_DISABLE_CLANG_TOOLS:BOOL=ON"

    - name: Build Ports
      shell: cmd
      working-directory: build/ports
      run: |
        ctest --output-on-failure --verbose
