# Copyright (c) 2023 Michael Beckh
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
name: Clean Packages
run-name: Clean Packages${{!inputs.delete && ' (Dry-Run)' || ''}}

on:
  workflow_call:
    inputs:
      older-than-days:
        description: Only delete versions older than this number of days (optional, default is 120).
        type: number
        default: 120
      delete:
        description: Do delete, default is output only (optional, default is false).
        type: boolean
        default: false
    secrets:
      VCPKG_REGISTRY_TOKEN:
        required: true

permissions: {}

jobs:
  clean_packages:
    name: Clean Packages${{!inputs.delete && ' (Dry-Run)' || ''}}
    runs-on: ubuntu-latest
    concurrency:
      group: vcpkg-registry-clean_packages
    continue-on-error: true

    steps:
    - name: Trigger ${{inputs.delete && 'Workflow' || 'Dry-Run'}}
      shell: bash
      env:
        OLDER_THAN_DAYS_JSON: ${{toJSON(inputs.older-than-days)}}
        DELETE_JSON: ${{toJSON(inputs.delete)}}
        REPOSITORY_JSON: ${{toJSON(github.repository)}}
        WORKFLOW_JSON: ${{toJSON(github.workflow)}}
        RUN_NUMBER_JSON: ${{toJSON(github.run_number)}}
        VCPKG_REGISTRY_TOKEN: ${{secrets.VCPKG_REGISTRY_TOKEN}}
      run: |
        url="$GITHUB_API_URL/repos/mbeckh/vcpkg-registry/actions/workflows/clean_packages.yml/runs?created=%3E%3D$(date -u -I -d "-1 week")&event=repository_dispatch&exclude_pull_requests=true"

        curl -D runs.json.headers --no-progress-meter \
             -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $VCPKG_REGISTRY_TOKEN" \
             "$url" > runs.json
        next=$(egrep -i '^link: ' runs.json.headers | grep -P -i -o '(?<=<)([\S]*)(?=>; rel="next")') || [[ $? == 1 ]]

        while [[ -n $next ]]; do
          curl -D "runs.json.headers" --no-progress-meter \
               -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $VCPKG_REGISTRY_TOKEN" \
               "$next" >> runs.json
          next=$(egrep -i '^link: ' runs.json.headers | grep -P -i -o '(?<=<)([\S]*)(?=>; rel="next")') || [[ $? == 1 ]]
        done

        [[ $RUNNER_DEBUG != 1 ]] || (echo "::group::$url" && cat runs.json && echo "::endgroup::")

        run_created=$(jq -r -s '
          .[]
          | .workflow_runs
          | map(select(.status | IN("completed", "success", "in_progress", "queued", "requested", "waiting", "pending")))
          | sort_by(.run_number)
          | .[-1:]
          | [ .run_number, .created_at]?
          | @sh' runs.json)

        [[ $DELETE_JSON == true ]] && mode='workflow' || mode='dry-run'
        if [[ -n $run_created ]]; then
          echo "Skipping $mode \"Clean Packages\" in repository mbeckh/vcpkg-registry, last run ${run_created%% *} created at ${run_created#* }."
        else
          echo "Trigger $mode \"Clean Packages\" in repository mbeckh/vcpkg-registry, last successful run was more than 1 week ago."
          # Try different repository to check rights
          curl -X POST --no-progress-meter \
               -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $VCPKG_REGISTRY_TOKEN" \
               "$GITHUB_API_URL/repos/mbeckh/vcpkg-registry/dispatches" \
               -d "{\"event_type\":\"clean_packages\",\"client_payload\":{\"older-than-days\":$OLDER_THAN_DAYS_JSON,\"delete\":$DELETE_JSON,\"origin\":{\"repository\":$REPOSITORY_JSON,\"workflow\":{\"name\":$WORKFLOW_JSON,\"run_number\":$RUN_NUMBER_JSON}}}}"
        fi
